# Generated by Django 4.1.7 on 2023-02-24 02:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRECIO', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('CLIENTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('PRODUCTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
    ]
