# Generated by Django 4.1.7 on 2023-02-24 16:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CANTIDAD_VENTA', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('PRECIO_VENTA', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('PRODUCTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('VENTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.venta')),
            ],
        ),
    ]
